### ISSUE TITLE
Errors from the `Handle<Type>` methods don't get propagated

### ISSUE THREAD

**Issue by shearn89** [remko/go-mkvparse#9]
I may not be doing things correctly, but I think this is a bug.

I'm trying to terminate processing early by having one of my methods (`HandleString`) return an `io.EOF` error when it's reached the end of what I need to process.

I was trying to work out why this wasn't doing anything, and it appears it's only the master elements that actually check if this error exists. See https://github.com/remko/go-mkvparse/blob/d7b7157edb37a0d789983e24bc189f46a0833c02/mkvparse.go#L266 for details.

I would have thought given we're returning errors from all the implemented `Handler` methods, they should do something.

Or am I using the code the wrong way?

**Comment by remko** [comment]
@shearn89 That looks wrong indeed. It seems that errors are only checked on HandleMaster*. Good catch!

Should be easy to fix. Will try to find some time to do it soon, unless you want to submit a PR?

**Comment by shearn89** [comment]
I'll try and submit a PR if I get time!
